In [105]:
import os
import csv

with open(r"C:\Users\nisch\Downloads\bank+marketing\bank\Original_data\bank-full.csv", 'r') as file:
    reader = csv.reader(file, delimiter=';')
    row1 = next(reader)
    print(row1)

['age', 'job', 'marital', 'education', 'default', 'balance', 'housing', 'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'y']

In [106]:
with open(r"C:\Users\nisch\Downloads\bank+marketing\bank\Original_data\bank.csv", 'r') as file:
    reader = csv.reader(file,)
    row2 = next(reader)
    print(row2)

['age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"']

In [107]:
print(row1 == row2)

False

In [108]:
target_row_from_bank_full = ['58', 'management', 'married', 'tertiary', 'no', '2143', 'yes', 'no', 'unknown', '5', 'may', '261', '1', '-1', '0', 'unknown', 'no']

with open(r"C:\Users\nisch\Downloads\bank+marketing\bank\Original_data\bank.csv", 'r') as file:
    reader = csv.reader(file, delimiter=';')
    found = any(row == target_row_from_bank_full for row in reader)
    print(found)

with open(r"C:\Users\nisch\Downloads\bank+marketing\bank\Original_data\bank-additional-full.csv", 'r') as file:
    reader = csv.reader(file, delimiter=';')
    found = any(row == target_row_from_bank_full for row in reader)
    print(found)

with open(r"C:\Users\nisch\Downloads\bank+marketing\bank\Original_data\bank-additional.csv", 'r') as file:
    reader = csv.reader(file, delimiter=';')
    found = any(row == target_row_from_bank_full for row in reader)
    print(found)

False
False
False

In [109]:
import pandas as pd

# Read all files with correct separator
df1 = pd.read_csv(r"C:\Users\nisch\Downloads\bank+marketing\bank\Original_data\bank-additional-full.csv", sep=';')
df2 = pd.read_csv(r"C:\Users\nisch\Downloads\bank+marketing\bank\Original_data\bank-additional.csv", sep=';')
df3 = pd.read_csv(r"C:\Users\nisch\Downloads\bank+marketing\bank\Original_data\bank-full.csv", sep=';')
df4 = pd.read_csv(r"C:\Users\nisch\Downloads\bank+marketing\bank\Original_data\bank.csv", sep=';')
print(df1.shape[1], df2.shape[1], df3.shape[1], df4.shape[1])
# Group files by their columns
# bank-additional-full & bank-additional likely have same columns
# bank-full & bank likely have same columns

# Combine files with matching columns
if list(df1.columns) == list(df2.columns):
    combined_additional = pd.concat([df1, df2], ignore_index=True).drop_duplicates()
    print(f"Combined additional: {len(combined_additional)} rows")

if list(df3.columns) == list(df4.columns):
    combined_bank = pd.concat([df3, df4], ignore_index=True).drop_duplicates()
    print(f"Combined bank: {len(combined_bank)} rows")

# Save separately if columns are different
combined_additional.to_csv(r"C:\Users\nisch\Downloads\bank+marketing\bank\Combined_data\combined_additional.csv", sep=';', index=False)
combined_bank.to_csv(r"C:\Users\nisch\Downloads\bank+marketing\bank\Combined_data\combined_bank.csv", sep=';', index=False)

21 21 17 17
Combined additional: 41176 rows
Combined bank: 45211 rows

In [110]:
df1.head(1)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [111]:
df1.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='object')

In [112]:
df3.head(1)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no

In [113]:
df3.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [114]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  y               41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB
None

In [115]:
print(df2.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4119 entries, 0 to 4118
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             4119 non-null   int64
 1   job             4119 non-null   object
 2   marital         4119 non-null   object
 3   education       4119 non-null   object
 4   default         4119 non-null   object
 5   housing         4119 non-null   object
 6   loan            4119 non-null   object
 7   contact         4119 non-null   object
 8   month           4119 non-null   object
 9   day_of_week     4119 non-null   object
 10  duration        4119 non-null   int64
 11  campaign        4119 non-null   int64
 12  pdays           4119 non-null   int64
 13  previous        4119 non-null   int64
 14  poutcome        4119 non-null   object
 15  emp.var.rate    4119 non-null   float64
 16  cons.price.idx  4119 non-null   float64
 17  cons.conf.idx   4119 non-null   float64
 18  euribor3m       4119 non-null   float64
 19  nr.employed     4119 non-null   float64
 20  y               4119 non-null   object
dtypes: float64(5), int64(5), object(11)
memory usage: 675.9+ KB
None

In [116]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

In [126]:
import os
import shutil

input_files = ['Combined_data\\combined_additional.csv', 'Combined_data\\combined_bank.csv']
out_dir = "final_datasets"
output_files = []

if out_dir and not os.path.exists(out_dir):
    os.makedirs(out_dir)
# Ensure output directories exist
import os
for file in input_files:
    file_name = os.path.split(file)[1]
    out_path = os.path.join(out_dir, file_name)
    output_files.append(out_path)
    shutil.copy(file, out_path)

print(input_files, output_files)


# Convert ; to , for each file
import csv
for input_file, output_file in zip(input_files, output_files):
    with open(input_file, 'r', newline='', encoding='utf-8') as infile, \
         open(output_file, 'w', newline='', encoding='utf-8') as outfile:
        reader = csv.reader(infile, delimiter=';')
        writer = csv.writer(outfile, delimiter=',')
        for row in reader:
            writer.writerow(row)

['Combined_data\\combined_additional.csv', 'Combined_data\\combined_bank.csv'] ['final_datasets\\combined_additional.csv', 'final_datasets\\combined_bank.csv']